# Generated by Django 2.2.3 on 2019-07-30 08:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('first_name', models.CharField(max_length=32, verbose_name='first name')),
                ('middle_name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='middle name')),
                ('last_name', models.CharField(max_length=32, verbose_name='last name')),
                ('phone_number', models.CharField(max_length=128, verbose_name='phone number')),
                ('email', models.CharField(max_length=32, verbose_name='email')),
                ('ticket', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ticket')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('first_name', 'last_name'),
            },
        ),
    ]
